apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: generic-pr-
  name: generic-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  params:
    - name: git-revision
      value: master
    - name: git-url
      value: https://github.com/dolun1119/shaolun-helloworld.git 
    - name: imageUrl
      value: dolun1119/spring-boot-demo
    - name: imageTag
      value: latest
    - name: kustomizePath
      value: "kustomize-demo/overlays/staging"
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-config
      secret:
        secretName: docker-config
  # serviceAccountName: tekton-build