apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Docker.
      default: ./
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: shaolun-demo-maven:latest
    
  steps:
    - name: maven
      image: maven:3.5.0-jdk-8-alpine
      workingDir: /workspace/source
      command: ["mvn"]
      args:
        - clean
        - install
    - name: test
      image: maven:3.5.0-jdk-8-alpine
      workingDir: /workspace/source
      command: ["ls"]