apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shaolun-demo-maven
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker
      resources:
        inputs:
          - name: source
            resource: source
    - name: deploy
      runAfter: [build]
      taskRef:
        name: deploy-kubectl
      resources:
        inputs:
          - name: source
            resource: source