apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  params:
    - name: kustomizePath
      description: path for kustomize command
  workspaces:
    - name: source
  steps:
    - name: print-parameters
      image: bash
      script: |
        ls $(workspaces.source.path); echo "$(workspaces.source.path)/$(params.kustomizePath)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl:v1.21.11
      # image: gcr.io/cloud-builders/kubectl
      imagePullPolicy: IfNotPresent
      command: ["kubectl"]
      args:
        - "apply"
        - "-k"
        - "$(workspaces.source.path)/$(params.kustomizePath)"
        # - "apply"
        # - "-f"
        # - "$(workspaces.source.path)/minikube-demo/demo-pod.yaml"