apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  params:
    - name: kustomizePath
      description: path for kustomize command
  workspaces:
    - name: source
  steps:
    - name: print-kustomize-path
      image: bash
      script: |
        echo "$(workspaces.source.path)/$(params.kustomizePath)"
        
    - name: run-kustomize
      image: lachlanevenson/k8s-kubectl:v1.21.11
      imagePullPolicy: IfNotPresent
      command: ["kubectl"]
      args:
        - "apply"
        - "-k"
        - "$(workspaces.source.path)/$(params.kustomizePath)"