apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-to-image
spec:
  params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
    - name: CHAINS-GIT_COMMIT
      description: Commit value
    - name: CHAINS-GIT_URL
      description: Git repo URL 
      
  workspaces:
    - name: source
    - name: dockerconfig
      mountPath: /kaniko/.docker

  steps:
    - name: print-git-info
      image: bash
      script: |
        echo $(params.CHAINS-GIT_COMMIT); echo $(params.CHAINS-GIT_URL)

    - name: maven
      image: maven:3.8.5-openjdk-11
      imagePullPolicy: IfNotPresent
      workingDir: $(workspaces.source.path)
      command:
        - mvn
      args:
        - clean
        - install
        # - -DskipTests
      volumeMounts:
        - name: m2
          mountPath: /root/.m2

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: IfNotPresent
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(params.imageUrl):$(params.imageTag)
        - --context=$(workspaces.source.path)

  volumes:
    - name: m2
      hostPath:
        path: /data/.m2

        