apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo-pod
  labels:
    app: demoApp
spec:
  containers:
    - name: kubernetes-demo-container
      image: dolun1119/spring-boot-demo:latest
      ports:
        - containerPort: 8080