apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo-pod
  labels:
    app: demoApp
spec:
  containers:
    - name: kubernetes-demo-container
      image: dolun1119/spring-boot-demo:latest
      # imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: TEST_GREETING
          value: "test-env"
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
