apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: print-parameters
      image: bash
      script: |
        ls; echo "test test"; pwd
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World"